### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jarelllama** [jarelllama/Blocklist-Checker#22]
Hi @iam-py-test, I know you like your statistics. This repo might interest you. Feel free to give me any feedback or ideas on integrations.

**Comment by iam-py-test** [comment]
Looks cool. May I try it out?
Thanks for pinging me.

**Comment by jarelllama** [comment]
You can give it a shot! But I just discovered some bugs regarding extracting the blocklist title and that some blocklists have carriage return characters I need to remove. Will fix in a couple hours, but otherwise everything works.

**Comment by iam-py-test** [comment]
Sorry about #43... Dumb idea, feel free to delete that issue.
