### ISSUE TITLE
The malicious website blocklist

### ISSUE THREAD

**Issue by iam-py-test** [jarelllama/Blocklist-Checker#42]
### Report for:

https://raw.githubusercontent.com/iam-py-test/my_filters_001/main/antimalware.txt

**Comment by jarelllama** [comment]
Looks like your content modifiers are getting flagged as invalid by the Hostlist compiler. Also breaks `sed` if I don't escape everything properly.

**Comment by iam-py-test** [comment]
Ah, makes sense.

**Comment by jarelllama** [comment]
I'll do an update later to strip the modifiers

**Comment by iam-py-test** [comment]
No worries.

**Comment by jarelllama** [comment]
Are there anything other stats I can include to make the report more useful?

**Comment by iam-py-test** [comment]
Useful stats? Maybe a redundant entry check, but other than that, no. I think this check covers all the helpful areas without displaying an overwhelming amount of information.
But one useless-but-cool stat would be [the number of entries per TLD](https://github.com/iam-py-test/tld_tracking/blob/main/output.md#the-malicious-website-blocklist) ([like ghosts](https://github.com/StevenBlack/ghosts)). Again, I don't really see a *purpose*, so feel free to decline.
Thanks
