### ISSUE TITLE
Data in CSV format

### ISSUE THREAD

**Issue by jarelllama** [jarelllama/Blocklist-Checker#63]
Hi @iam-py-test, if I schedule a daily CSV report for each blocklist submitted here, would you be interested in using the data? Generating graphs is out of scope is currently out of scope for me.

**Comment by iam-py-test** [comment]
> would you be interested in using the data?

Possibly, though I'm not sure on how I would use it.

**Comment by xRuffKez** [comment]
[9a7b950](https://github.com/jarelllama/Blocklist-Checker/pull/100/commits/9a7b95001b8d784a6ff3420426d308e88ee2e00f)
